version: '3.7'

services:
  postgres:
    image: postgres
    container_name: social-media-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTRES_DB: social-media
      POSTGRES_PASSWORD: root

volumes:
  postgres-data: